title: Global Optimization for Geometric Understanding with Provable Guarantees
description: Title
sitename: GlobalOptimization@ICCV2019
baseurl: ''

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Makefile